[[FFTW]]
arch = "aarch64"
git-tree-sha1 = "6115fc8b0ecba293441b54f11f0c6c76fcb3cd42"
os = "macos"

    [[FFTW.download]]
    sha256 = "9f410a88ead16f5d1b1d74cfbe8eb7a6bef59878d4fd05392f4b2f35d509a65d"
    url = "https://github.com/giordano/FFTW_jll.jl/releases/download/FFTW-v3.3.9+8/FFTW.v3.3.9.aarch64-apple-darwin.tar.gz"
